### ISSUE TITLE
Used a lot of vars

### ISSUE THREAD

**Issue by Niaz-Ul-Haque** [joelazwar/linkChek#1]
I remember during my semester 4, my prof told me to use let most of the time, in fact not to use var. As you are doing it in a smaller function block, let will be a better option. 

Also, I can see that you used var for the regex variable too, I don't think you will change the regex anytime soo. So, I suggest you
can make it a const.

![1](https://user-images.githubusercontent.com/48073912/93936751-a3e2f000-fcf4-11ea-9767-6a2f44d35042.PNG)
![2](https://user-images.githubusercontent.com/48073912/93936753-a3e2f000-fcf4-11ea-8fb1-c4fe3b24c86b.PNG)

**Comment by joelazwar** [comment]
fixed
