### ISSUE TITLE
I found out this bug, the count is the same and want to add some options. Is it ok if I go for it?

### ISSUE THREAD

**Issue by StellaJung-Student** [joelazwar/linkChek#5]
![image](https://user-images.githubusercontent.com/59578350/94816018-38baad00-03c9-11eb-8fb1-e6188b9c1f35.png)

The first option I want to add is http or https option. 
For example If I choose https then the http url will be replaced with https url to check.

Another option I want to add is time out option.

**Comment by joelazwar** [comment]
Hi Stella, that would be perfectly fine. Anyways I'm reviewing your pull request now :)
